/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mars_ndksimple_01_HelloNDK */

#ifndef _Included_com_mars_ndksimple_01_HelloNDK
#define _Included_com_mars_ndksimple_01_HelloNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mars_ndksimple_01_HelloNDK
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mars_ndksimple_101_HelloNDK_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
